spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${PSQL_DB_PASSWORD}
    url: jdbc:postgresql://${PSQL_DB_HOST}:${PSQL_DB_HOST}/${PSQL_DB_NAME}
    username: ${PSQL_DB_USERNAME}

    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000

  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: file:/upload



