spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: c610f7adb02a55dd7c35bf71fe1cf03c5c6c819b2303d104ae8113ba37c29505
    url: jdbc:postgresql://ec2-3-228-117-228.compute-1.amazonaws.com:5432/d5fqelkp50lmhm
    username: onophtyiuzcmll


  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: create-drop